# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: c4_graph.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'c4_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x34_graph.proto\"$\n\x0cNeighborData\x12\x14\n\x0cneighbor_ids\x18\x01 \x03(\r\"j\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\r\x12\x11\n\x07\x66lat_ss\x18\x02 \x01(\x0cH\x00\x12&\n\rneighbor_data\x18\x03 \x01(\x0b\x32\r.NeighborDataH\x00\x12\x0b\n\x03rep\x18\x04 \x01(\x0c\x42\x0e\n\x0cnode_content\"5\n\x07\x44\x61taset\x12\x14\n\x05nodes\x18\x01 \x03(\x0b\x32\x05.Node\x12\x14\n\x0croot_node_id\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'c4_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NEIGHBORDATA']._serialized_start=18
  _globals['_NEIGHBORDATA']._serialized_end=54
  _globals['_NODE']._serialized_start=56
  _globals['_NODE']._serialized_end=162
  _globals['_DATASET']._serialized_start=164
  _globals['_DATASET']._serialized_end=217
# @@protoc_insertion_point(module_scope)
