syntax = "proto3";

message Branch {
  bytes rep = 1; // Sequence of 3-byte entries constructing the input
  oneof value {
    uint32 move = 2; // Always 3 bytes: response is in [0...7] inclusive.
    uint32 steady_state = 3; // Index into SteadyStates.steadystates to follow from here.
  }
}

message Branches {
  repeated Branch branches = 1;
}

message SteadyState {
  bytes steadystate = 1; // levels 0-9, 4 bits per cell, 42 cells column-major bottom-to-top,
                         // first cell in the high nibble -> 21 bytes
}

message SteadyStates {
  repeated SteadyState steadystates = 1;
}

message Solution {
  Branches branches = 1;
  SteadyStates steadystates = 2;
}
