# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: format.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'format.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x66ormat.proto\"#\n\x06\x42ranch\x12\x0b\n\x03rep\x18\x01 \x01(\x0c\x12\x0c\n\x04move\x18\x02 \x01(\r\"%\n\x08\x42ranches\x12\x19\n\x08\x62ranches\x18\x01 \x03(\x0b\x32\x07.Branch\"\"\n\x0bSteadyState\x12\x13\n\x0bsteadystate\x18\x01 \x01(\x0c\"2\n\x0cSteadyStates\x12\"\n\x0csteadystates\x18\x01 \x03(\x0b\x32\x0c.SteadyState\"M\n\x08Solution\x12\x1b\n\x08\x62ranches\x18\x01 \x01(\x0b\x32\t.Branches\x12$\n\rsteady_states\x18\x02 \x01(\x0b\x32\r.SteadyStatesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'format_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRANCH']._serialized_start=16
  _globals['_BRANCH']._serialized_end=51
  _globals['_BRANCHES']._serialized_start=53
  _globals['_BRANCHES']._serialized_end=90
  _globals['_STEADYSTATE']._serialized_start=92
  _globals['_STEADYSTATE']._serialized_end=126
  _globals['_STEADYSTATES']._serialized_start=128
  _globals['_STEADYSTATES']._serialized_end=178
  _globals['_SOLUTION']._serialized_start=180
  _globals['_SOLUTION']._serialized_end=257
# @@protoc_insertion_point(module_scope)
